[GH-43] added cypress
oseducation/knowledge-graph pull request #84
Opened 2023-04-23 16:51 UTC by amnesiac09

Added e2e testing support cypress on webapp and implemented some basic tests for login and register page. To run these tests, you need to run the go application itself, run react app and then run `npx cypress open`

2023-04-23 17:31 UTC, Tochi999 approved these changes

2023-04-23 18:15 UTC, iomodo requested changes
Looks great @amnesiac09 !
Couple of questions below.
Also could we add e2e tests to the GitHub pipeline? You can see details [here](https://docs.cypress.io/guides/continuous-integration/github-actions)

2023-04-29 09:53 UTC, amnesiac09 commented on webapp/cypress/e2e/register_test.cy.ts
> +        cy.intercept('POST', '/api/v1/users/register', (req) => {
I thought it would be better if frontend tests didn't actually send requests to the db and add entries in there.

2023-04-29 10:21 UTC, iomodo commented on webapp/cypress/e2e/register_test.cy.ts
> +        cy.intercept('POST', '/api/v1/users/register', (req) => {
It's better to do the whole end-to-end testing(from user's perspective) here, with DB included.

2023-04-29 10:24 UTC, amnesiac09 commented on webapp/cypress/e2e/register_test.cy.ts
> +        cy.intercept('POST', '/api/v1/users/register', (req) => {
But when this test once adds that user to the db, when you run it again, it returns "user already exists" error, so this test only works once. Should I remove the user from db once the test is finished?

2023-05-01 11:11 UTC, iomodo commented on webapp/cypress/e2e/register_test.cy.ts
> +        cy.intercept('POST', '/api/v1/users/register', (req) => {
We could create a new DB on every test case, or we could mock api layer for now, if setting up DB is too much work for this ticket.

2023-05-02 12:34 UTC, amnesiac09 commented on webapp/cypress/e2e/login_test.cy.ts
> +        cy.get('input[name="email"]').type('cypresstest@gmail.com');
I changed the test so it doesn't actually require to have that user in the db, it just mocks the response from api

2023-05-02 16:57 UTC, iomodo approved these changes

2023-05-02 16:57 UTC, merged